### ISSUE TITLE
Forward all events from kafka topic to websocket connection

### ISSUE THREAD

**Issue by Bad-Science** [YACS-RCOS/yacs-notifications#7]
As a first step towards getting a useful websocket API, we will simply take all events consumer from the karafka consumer created for #5, and send them as messages on a websocket connection. The messages should follow the JSON:API format for a single object.

**Comment by bdieu178** [comment]
#Notes to self 
-[] Send to the WebSocket instead of the stdin

**Comment by Bad-Science** [comment]
Additional info:

At least for now, we want this to all occur in a single process. Right now the entrypoint is `karafka.rb`. That can remain the entrypoint for now. You will want to create a file/class to handle the websocket server as per #8 . This server should then be activated in the `karafka.rb` file. You can then use an in-process pub/sub or observer to send events consumed by karafka over the websocket connection

**Comment by bdieu178** [comment]
@Bad-Science @huangmj7 
I've enabled the karafka consumer to publish to the Iodione pubsub system. Working on formatting the output and checking the server

```
notifications_1  | Consumer message sent to websocket
notifications_1  | I, [2018-08-07T00:54:51.384357 #6]  INFO -- : Inline processing of topic course_change with 1 messages took 3.84 ms
notifications_1  | I, [2018-08-07T00:54:51.384692 #6]  INFO -- : 1 messages on course_change topic delegated to CourseConsumer
notifications_1  | Consumer message sent to websocket
notifications_1  | I, [2018-08-07T00:54:51.387295 #6]  INFO -- : Inline processing of topic course_change with 1 messages took 2.14 ms
notifications_1  | I, [2018-08-07T00:54:51.387379 #6]  INFO -- : 1 messages on course_change topic delegated to CourseConsumer
notifications_1  | Consumer message sent to websocket
notifications_1  | I, [2018-08-07T00:54:53.451256 #6]  INFO -- : Inline processing of topic course_change with 1 messages took 4.11 ms
notifications_1  | I, [2018-08-07T00:54:53.460466 #6]  INFO -- : 1 messages on course_change topic delegated to CourseConsumer
notifications_1  | Consumer message sent to websocket
notifications_1  | I, [2018-08-07T00:54:54.408911 #6]  INFO -- : Inline processing of topic section_change with 1 messages took 1.63 ms
notifications_1  | I, [2018-08-07T00:54:54.409102 #6]  INFO -- : 1 messages on section_change topic delegated to SectionConsumer
notifications_1  | Consumer message sent to websocket
notifications_1  | I, [2018-08-07T00:54:54.410566 #6]  INFO -- : Inline processing of topic section_change with 1 messages took 0.8 ms
notifications_1  | I, [2018-08-07T00:54:54.410693 #6]  INFO -- : 1 messages on section_change topic delegated to SectionConsumer
notifications_1  | Consumer message sent to websocket
notifications_1  | I, [2018-08-07T00:54:54.412780 #6]  INFO -- : Inline processing of topic section_change with 1 messages took 1.27 ms
notifications_1  | I, [2018-08-07T00:54:54.413418 #6]  INFO -- : 1 messages on section_change topic delegated to SectionConsumer
```

I got this point, by reverting to older versions of Iodine & Plezi while calling onto Iodine directly for using pub/sub methods

Current implementation:
```
require 'karafka'
require 'iodine'
require_relative 'application_consumer'

class CourseConsumer < ApplicationConsumer
  def consume
    unless params.nil?
        @notifications = params.to_s
        ::Iodine::publish channel: "notifications", message: "#{@notifications}"
        puts "SectionsConsumer sent message to websocket"
    end	
  end
end

```

**Comment by bdieu178** [comment]
@huangmj7  @Bad-Science  I'm making progress

```
172.18.0.1 - - [Tue, 6 Aug 2018 03:04:59 GMT] "GET /notifications HTTP/1.1" 101 -- 50ms
Iodine caught an unprotected exception - ArgumentError: wrong number of arguments (given 0, expected 1)
/usr/src/app/app/controllers/eventstream.rb:10:in `on_open'
Iodine caught an unprotected exception - ArgumentError: wrong number of arguments (given 1, expected 2)
/usr/src/app/app/controllers/eventstream.rb:20:in `on_message'
```
